name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make run
      run: make run
    - name: make gif
      run: make gif
    - name: make mp4
      run: make mp4